### ISSUE TITLE
When given a font manifest (fonts and styles requested), provide an output indicating location of those paths

### ISSUE THREAD

**Issue by ronaldtse** [fontist/fontist#106]
When given a font manifest (fonts and styles requested), provide an output indicating location of those paths. 

The font manifest should be in yaml or in json. The returned output should be in yaml or in json.

**Comment by ronaldtse** [comment]
One use case is https://github.com/metanorma/mn2pdf , where it is necessary for the PDF engine to find out the absolute paths of all fonts used (some fonts from Fontist, some from system).

**Comment by alexeymorozov** [comment]
Something like this?

```sh
$ cat manifest.yml
---
Andale Mono:
- Regular
Courier New:
- Bold
Helvetica:
- Regular

$ fontist paths manifest.yml
---
Andale Mono:
  Regular: "/Users/user/.fontist/fonts/courbd.ttf"
Courier New:
  Bold: "/Users/user/.fontist/fonts/AndaleMo.TTF"
Helvetica:
  Regular: "/System/Library/Fonts/Helvetica.ttc"
```

**Comment by ronaldtse** [comment]
Yes, exactly.

**Comment by alexeymorozov** [comment]
@ronaldtse Please clarify: both json or yaml should be supported or it's a choice for implementation? Thanks :)

**Comment by ronaldtse** [comment]
@alexeymorozov YAML is certainly easier here, thanks.

**Comment by alexeymorozov** [comment]
Ok :) Then it’s ready for review https://github.com/fontist/fontist/pull/157

**Comment by ronaldtse** [comment]
Closing since #157 is merged.
