### ISSUE TITLE
If user doesn't have some fonts requested by user application, prompt the user application

### ISSUE THREAD

**Issue by ronaldtse** [fontist/fontist#116]
We need to move this message back to metanorma-cli. i.e.

```
        Metanorma has detected that you do not have the necessary fonts installed
        for PDF generation. Without those fonts, the generated PDF will use
        generic fonts that may not resemble the desired styling.
```

The steps should be:
1. Metanorma asks Fontist to check and install some fonts.
2. Fontist checks the fonts, installs necessary ones, and returns with value Metanorma that some fonts need to be installed and need license acceptance.
3. Metanorma tells user that the font licenses need to be accepted (unless `metanorma setup --accept-all-font-licenses` is called (some command to that effect)). Metanorma prints out this message, and hands back control to Fontist. (Maybe this message was provided by Metanorma to Fontist in the initial call, i.e. `if_requires_license: "... message..."`)
4. Fontist reads the YES/NO and continues.

_Originally posted by @ronaldtse in https://github.com/fontist/fontist/pull/102#issuecomment-671006037_

**Comment by abunashir** [comment]
@ronaldtse: Added on the attached PR, let me know if there is anything else.

**Comment by ronaldtse** [comment]
Thanks @abunashir !
