### ISSUE TITLE
Maintain an index for the formulas repo so that font searching is fast and correct

### ISSUE THREAD

**Issue by ronaldtse** [fontist/fontist#125]
Since there are going to be thousands of formulas in the formula repo, we don't want the gem to parse all the files on every command. Therefore the formula repo should have a pre-built index, such as of font names and font styles for quick access to formulas.

There should be some script that rebuilds the font formula index (e.g. `fontist rebuild-index`). The method to read / update the index should be implemented in the fontist gem. This index should always be included in the formula repository so it is immediately pullable with the repo (or it is built by user system on first fetch of the formula repo?).

This should be done after #118 #124 .

**Comment by ronaldtse** [comment]
This is related to #175 , where fonts are matching the wrong names.

**Comment by alexeymorozov** [comment]
The index could have this structure:

```yaml
Work Sans:
  Regular: work_sans.yml
  Bold: work_sans.yml
Andale Mono:
  Regular: andale.yml
```

This would allow to search by font and by font+style.

Will try to replace search in `Fontist::Formula` with this implementation.

**Comment by alexeymorozov** [comment]
I think, could we get rid of search by formulas? There are cases, when font name in a formula differs from info in font file.

For example:

```yaml
# courier.yml
fonts:
- name: Courier
```

But

```bash
$ otfinfo -i ~/.fontist/fonts/cour.ttf | grep Family
Family:              Courier New
```

It is `Courier New` but aliased as just `Courier` in formulas.

To be able to search just by `Courier`, fontist have to scan through all formulas, find filenames associated with this font and then scan system for these filenames.

If we adjust formula information to be exactly the same as in font files (`otfinfo`), we could skip loading formulas for all search operations. But also fontist would loose ability to define custom names for fonts (like `Courier` -> `Courier New`).

Do we need the ability to alias fonts? Or is it better to avoid multiple names for the same font?
