### ISSUE TITLE
Interesting read: Most popular article

### ISSUE THREAD

**Issue by abunashir** [fontist/fontist#126]
Hey Guys, just came across this one and thought it would be an interesting read - https://www.lifehack.org/428846/top-20-most-popular-fonts-of-all-time, should we consider adding these missing and open-licensed fonts at some point, so people can easily benefit from the library.

Btw, Good job @alexeymorozov on adding the Google fonts, you did a pretty amazing job there ❤️ 

cc: @ronaldtse, @alexeymorozov

**Comment by ronaldtse** [comment]
@abunashir would be great to allow installation of fonts mentioned in the article, but most of them are not open.

Fonts from the list:

1. Helvetica (Max Miedinger, 1957)
2. Baskerville (John Baskerville, 1757)
3. Times (Stanley Morison, 1931)
4. Akzidenz Grotesk (Brethold Type Foundry, 1896)
5. Gotham (Hoefler and Frere- Jones, 2000)
6. Bodoni (Giambattista Bodoni, 1790)
7. Didot (Firmin Didot, 1784-1811)
8. Futura (Paul Renner, 1927)
9. Gill Sans (Eric Gill, 1928)
10. Frutiger (Adrian Frutiger, 1977)
11. Bembo (Aldus Manutius, Frank Hinman Pierpont and Francesco Griffo, 1929)
12. Rockwell (Monotype Foundry, 1934)
13. Franklin Gothic (Morris Fuller Benton, 1903)
14. Sabon (Jan Tschichold, 1966)
15. Georgia (Matthew Carter, 1993)
16. Garamond (Claude Garamond, 1530)
17. News Gothic (Morris Fuller Benton, 1908)
18. Myriad (Robert Slimbach, Carol Twombly, Christopher Slye and Fred Brady, 1992)
19. Mrs Eaves (Zuzana Licko, 1996)
20. Minion (Rober Slimbach, 1990)


Open fonts available:

1. Helvetica => Arial (formula exists)
2. Baskerville [X]
3. Times => Times New Roman (formula exists)
4. Akzidenz Grotesk [X]
5. Gotham [X]
6. Bodoni => Bodoni* (https://www.fontsquirrel.com/fonts/bodoni1)
7. Didot => Theano Didot (https://www.fontsquirrel.com/fonts/theano-didot)
8. Futura => Passata (https://medarbejdere.au.dk/en/administration/communication/guidelines/guidelinesforfonts/downloadfonts/) (Wikipedia: Passata is a modernized version of Futura)
9. Gill Sans [X]
10. Frutiger (Adrian Frutiger, 1977)
11. Bembo (Aldus Manutius, Frank Hinman Pierpont and Francesco Griffo, 1929)
12. Rockwell (Monotype Foundry, 1934)
13. Franklin Gothic (Morris Fuller Benton, 1903)
14. Sabon (Jan Tschichold, 1966)
15. Garamond => EB Garamond (#120)
16. Georgia => (formula exists)
17. News Gothic => Adobe Source Sans (formula exists), News Cycle (https://www.fontsquirrel.com/fonts/news-cycle)
18. Myriad => #128
19. Mrs Eaves [X]
20. Minion => #128

**Comment by ronaldtse** [comment]
These fonts may relate to "Font Compatibility" #119 but it's not something to be done in this ticket. We also can't use the fonts that are not openly available.

So this task is the implementation of these fonts as formulas:

- Bodoni => Bodoni* (https://www.fontsquirrel.com/fonts/bodoni1)
- Didot => Theano Didot (https://www.fontsquirrel.com/fonts/theano-didot)
- Futura => Passata (https://medarbejdere.au.dk/en/administration/communication/guidelines/guidelinesforfonts/downloadfonts/) (Wikipedia: Passata is a modernized version of Futura)
- Garamond => EB Garamond (fontist/formulas#9)
- News Gothic => Adobe Source Sans (formula exists), News Cycle (https://www.fontsquirrel.com/fonts/news-cycle)
- Myriad => #128
- Minion => #128

**Comment by ronaldtse** [comment]
We can close this once we implement #110 and #119.

**Comment by ronaldtse** [comment]
Closing this for now, we've got most of the fonts in. #110 and #119 remain.
