### ISSUE TITLE
Install/check fonts using a "font manifest"

### ISSUE THREAD

**Issue by ronaldtse** [fontist/fontist#15]
A font manifest is a hash (can be represented by a YAML file) that provides a key-value mapping of "font name" to "font path".

When Fontist is given a list of "font names" to query, it can output a "font manifest" that lists out for each "font name" the installed "font path".

This font manifest can be directly utilized by font using applications.

**Comment by ronaldtse** [comment]
This means that:


1. Fontist should be given a "font manifest" that describes what fonts are required to be installed. 
e.g. 

```sh
# fontist install fonts.yml
```

```ruby
Fontist.install('xxx.yaml')
```

2. Fontist can report back status of fonts

```sh
# fontist status fonts.yml
```

```ruby
Fontist.status('xxx.yaml')
# => which fonts are installed, which styles we have, etc.
```

**Comment by abunashir** [comment]
@ronaldtse: Do we have a finalized version for the font manifesto we want to support?

**Comment by ronaldtse** [comment]
Since #106 #157 are done it is time to install fonts using a manifest. Thanks @alexeymorozov !

**Comment by alexeymorozov** [comment]
Done in #158
