### ISSUE TITLE
Creating a Fontist font directory

### ISSUE THREAD

**Issue by ronaldtse** [fontist/fontist#18]
When the user wants to install fonts using Fontist, we should create a `~/.fontist/fonts` directory to install all necessary fonts into. 

We need the user to install fonts him/herself because of font licensing for distributions -- users can download the fonts freely, but we cannot distribute them. Even on Ubuntu where there is a package to install Windows fonts, we cannot depend on it because it is in the "contrib" repository and is not enabled by default.

_Originally posted by @ronaldtse in https://github.com/fontist/fontist/issues/3#issuecomment-619563007_

**Comment by abunashir** [comment]
This already done, we've ruby [`Fontist. fontist_path`](https://github.com/fontist/fontist/blob/master/lib/fontist.rb#L34) and it will return the global font directory.

**Comment by ronaldtse** [comment]
Excellent. Thanks!
