### ISSUE TITLE
Allow override font installation path 

### ISSUE THREAD

**Issue by CAMOBAP** [fontist/fontist#181]
### Intro

In the scope of https://github.com/metanorma/metanorma-docker/issues/62 we need somehow pass fonts to melanoma in docker. @ronaldtse suggested declaring special `VOLUME /config/fonts` to mount path on `docker run`

### Proposed solution

If we can do this with an environment variable that will be the perfect solution from my point of view. We can discuss name of this env var, I propose 'FONTIST_PATH`

@ronaldtse @abunashir @alexeymorozov how do you think?

**Comment by ronaldtse** [comment]
@CAMOBAP agree. So `FONTIST_PATH` is used for Metanorma to pass to Fontist, and Fontist will install or use the fonts there.

**Comment by CAMOBAP** [comment]
@ronaldtse in case of env variables we only need modify fontist code, no need to modify metanorma code to explicitly pass font installation path.

But I can agree with other possible implementations too, like explicitly pass it via param of metanorma cli, but in this case it will not very useful for user because they will need to pass it on each call. While env var can be defined once

**Comment by alexeymorozov** [comment]
Seems it's a good solution 👍 

If the FONTIST_PATH environment variable is set, fontist would use it as a directory for fonts, otherwise fallback to `~/.fontist/fonts`.

**Comment by alexeymorozov** [comment]
One addition: it would install fonts not directory to `FONTIST_PATH`, but to `FONTIST_PATH/fonts`.
