### ISSUE TITLE
Can we have release for Fontist::Manifest::Locations.from_hash(manifest) API

### ISSUE THREAD

**Issue by CAMOBAP** [fontist/fontist#185]
Can we have release for [Fontist::Manifest::Locations.from_hash(manifest) API](
https://github.com/fontist/fontist/commit/93b8ac6576495da2b01c5e4b357d439880b54d72)

P.S. if you interested I can adapt this https://github.com/metanorma/mn2pdf-ruby/blob/master/.github/workflows/release.yml workflow to the project. And releasing will be a bit simpler

**Comment by alexeymorozov** [comment]
Of course :) Released v1.7.3

This workflow seems interesting, thanks!

Currently fontist release is done with:

```
gem bump
rake release
```
