### ISSUE TITLE
Manifest will corrupt when running more than a single Fontist instance

### ISSUE THREAD

**Issue by opoudjis** [fontist/fontist#200]
I ran two rspec sessions on metanorma-iso simultaneously. As  a result, my font manifest ~/.fontist/system_index.yml became corrupted:

````
- :path: "/Users/nickn/Library/Fonts/NotoSansArabic-ExtraBold.ttf"
  :full_name: Noto Sans Arabic ExtraBold
  :family_name: Noto Sans Arabic
  :type: ExtraBold
- :path: "/Users/nickn/Library/Fonts/NotoSans-CondensedExtraLight.ttf"
  :full_name: Noto Sans Conde
- :path: "/Users/nickn/Library/Fonts/NotoSansArabic-SemiCondensedThin.ttf"
  :full_name: Noto Sans Arabic SemiCondensed Thin
  :family_name: Noto Sans Arabic
  :type: SemiCondensed Thin
````

1. Ensure access to fontist is thread-safe
2. Issue a warning if you detect that the font entry is corrupted (missing one if its attributes) 
3. Ensure that if a font entry is corrupted, it does not crash:

````
 def find(font, style)
      fonts = system_index.select do |file|
        file[:family_name].casecmp?(font) &&
          (style.nil? || file[:type].casecmp?(style))
      end

      fonts.empty? ? nil : fonts
    end
````

That should be `file&.dig(:family_name)&.casecmp?(font)`, etc.

**Comment by ronaldtse** [comment]
We could add a lock file during access, just like Git does to the Git index.

**Comment by alexeymorozov** [comment]
Implemented a locking mechanism for this and other cases.

@opoudjis,

If there would be a warning instead of an error, fontist could not find a font with a corrupted data. How about it would throw an exception with a descriptive message, saying that the index is corrupted?

**Comment by ronaldtse** [comment]
> Issue a warning if you detect that the font entry is corrupted (missing one if its attributes)

It would be better to throw an error if an index is corrupted because it could indicate further issues, e.g. even if the structure is correct, the content is corrupted.

> Ensure that if a font entry is corrupted, it does not crash:

It should fail gracefully and prompt the user to re-build or refetch the index, not crash.
