### ISSUE TITLE
Parameterise font name in Fontist::Errors::NonSupportedFontError

### ISSUE THREAD

**Issue by opoudjis** [fontist/fontist#201]
When a font being installed by a metanorma flavour is not supported, metanorma-standoc prints its own error message:

https://github.com/metanorma/metanorma-standoc/blob/046b4ed4cf6b767a625c818cb4c0cd1646cce3f0/lib/asciidoctor/standoc/converter.rb#L142

````
rescue Fontist::Errors::NonSupportedFontError => e
          font = /Font '([^']+)'/.match(e.to_s)[1]
          Metanorma::Util.log("[fontist] '#{font}' font is not supported. " \
            "Please go to github.com/metanorma/metanorma-#{flavor_name}/issues" \
            " to report this issue.", :info)
````

I've had to insert the ugly `font = /Font '([^']+)'/.match(e.to_s)[1]`, because the original developer didn't define `font` at all.

It would of course be far preferable if the raised error could give the font name as a parameter, as in https://stackoverflow.com/questions/11636874/raise-custom-exception-with-arguments, so that I can instead just use `e.font`.

**Comment by ronaldtse** [comment]
Thanks for the suggestion @opoudjis , this is indeed necessary. @alexeymorozov could you help fix? Thanks!

**Comment by alexeymorozov** [comment]
Yes, let's done it, looks as a nice feature to me also :)
