### ISSUE TITLE
Fontist::Errors::InvalidResourceError Invalid URL: https://github.com/stipub/stixfonts/raw/master/zipfiles/STIXv2.0.2.zip

### ISSUE THREAD

**Issue by CAMOBAP** [fontist/fontist#203]
Fontist::Errors::InvalidResourceError:
        asciidoctor: FAILED: spec/assets/xref_error.adoc: Failed to load AsciiDoc document - Invalid URL: https://github.com/stipub/stixfonts/raw/master/zipfiles/STIXv2.0.2.zip

Full log https://github.com/metanorma/metanorma-cc/runs/1625768687?check_suite_focus=true

**Comment by alexeymorozov** [comment]
Thank you! Will fix.

Relates to https://github.com/fontist/formulas/issues/66

**Comment by alexeymorozov** [comment]
Updated the formula. Should be fixed now.
