### ISSUE TITLE
[FEATURE] Add --no-progress flag

### ISSUE THREAD

**Issue by CAMOBAP** [fontist/fontist#213]
### Problem

Our CI logs suffer from a lot of logs like this:

```
...
Downloads: 96MB/96MB (100.00%)
...
```

It's hard to open/browse them

### Proposed solution

Previously we have absolutely the same issue with `chocolatey install`, till we find that there is `--no-progress` option. I propose to implement the same mechanism in `fontist`.

Once this option passed `fontist ...` should not print download progress. Because it already prints the message `Downloading font "FONT_NAME" from URL`

@ronaldtse @alexeymorozov how do you think about this request?

**Comment by ronaldtse** [comment]
Agree, we should have a "quiet" or "no-progress" option to hide interactive download progress.

e.g. Regular (interactive)
```sh
[fontist] download file xxx 156MB begin.
[fontist] download file xxx: 50/156MB (32%)    # <= flashing line, something like this
[fontist] download file xxx 156MB done.
...
```

e.g. `no-progress`:
```sh
[fontist] download file xxx 156MB begin.
[fontist] download file xxx 156MB done.
...
```

e.g. `quiet`:
```sh
...
```
