### ISSUE TITLE
Crash in fontist if the formulas are of different versions

### ISSUE THREAD

**Issue by ronaldtse** [fontist/fontist#235]
When I have locally installed fontist, and I have an instance of fontist inside a gem bundle, if the two versions of fontist are different but share the same local fontist formula cache, one of the fontist instances may crash.

We need a way to keep different versions of fontist formulas.

**Comment by alexeymorozov** [comment]
I think to implement it the following way. Isolate formulas repos with separate directories. The file structure could be:

```
.fontist
├── downloads
├── fonts
└── versions
    ├── master
    │   ├── filename_index.yml
    │   ├── formula_index.yml
    │   └── formulas
    │       ├── Formulas
    └── v2
        ├── filename_index.yml
        ├── formula_index.default_family.yml
        ├── formula_index.preferred_family.yml
        └── formulas
            ├── Formulas
```

This way there is no need to update formulas every time fontist is switched between different versions. And also allows to use different versions of fontist simultaneously.

**Comment by ronaldtse** [comment]
Agree @alexeymorozov , let's proceed. Thanks!
