### ISSUE TITLE
Fix private fonts -- git repo for fontist/private-formulas changed to `main` branch

### ISSUE THREAD

**Issue by ronaldtse** [fontist/fontist#242]
I've changed the main branch of fontist/private-formulas to `main`. @alexeymorozov can you please help update? Thanks.

**Comment by alexeymorozov** [comment]
Of course. We have two repos:

- [fontist/formulas-private](https://github.com/fontist/formulas-private) (contains README)
- [metanorma/fontist-formulas-private](https://github.com/metanorma/fontist-formulas-private) (contains formulas)

[metanorma/fontist-formulas-private](https://github.com/metanorma/fontist-formulas-private) is in use now. I've pushed the main branch to it, and it's can be marked as default. Let's move README there?

**Comment by ronaldtse** [comment]
Yes please, can you help do that?

**Comment by alexeymorozov** [comment]
Done, updated both branches.

**Comment by alexeymorozov** [comment]
We may need to set the `main` branch as default so changes work.

https://github.com/metanorma/fontist-formulas-private/branches

**Comment by ronaldtse** [comment]
<img width="621" alt="Screenshot 2021-09-17 at 10 00 45 AM" src="https://user-images.githubusercontent.com/11865/133711853-d28a95a2-1855-462a-ba81-e293ec436bc4.png">

Done.
