### ISSUE TITLE
Private repositories: document that it can be HTTPS or SSH Git repos

### ISSUE THREAD

**Issue by ronaldtse** [fontist/fontist#245]

**Comment by ronaldtse** [comment]
Do we also need to run `fontist repo update reponame` after `fontist repo setup reponame`?

**Comment by alexeymorozov** [comment]
`update` may be run only if there is a need to fetch new or changed formulas, since `setup` initially fetches all current formulas. Will document it.

**Comment by ronaldtse** [comment]
And when I do fontist update will it also update the private repos?

**Comment by alexeymorozov** [comment]
Currently it wouldn't, but I see we need to update them too?

**Comment by ronaldtse** [comment]
Yeah let’s update them on the “update” command and we can also check if the access to the private formula repositories still work. If any of them don’t we should display some error message and advice to user on how to update the repo address.
