### ISSUE TITLE
Add possibility to install whole formula

### ISSUE THREAD

**Issue by CAMOBAP** [fontist/fontist#263]
### Intro 

Recently I have worked on the task which was related to replacement `apt-get install ttf-mscorefonts-installer` with `fontist` command.
Here is commit https://github.com/metanorma/mn2pdf/commit/364a47e2fdcd5be8eb5a5148328c3ce246591e79

I needed to write a manifest for those fonts, even while all these fonts available in a single [webcore](https://github.com/fontist/formulas/blob/v2/Formulas/webcore.yml) formula

### Proposal

It will be nice to have a possibility to install formula in a single command like `fontist install --formula webcore`

Because we potentially may need to install this collection in other places

----

@alexeymorozov @ronaldtse let me know how do you think about this feature?

**Comment by ronaldtse** [comment]
@CAMOBAP fully agree! That would be very useful. Needing to prepare a font manifest is complex.
