### ISSUE TITLE
How to disable system output for `Install.from_hash`

### ISSUE THREAD

**Issue by CAMOBAP** [fontist/fontist#276]
- https://github.com/metanorma/metanorma-cli/issues/267 - original ticket

We would like to reduce the output amount in metanorma, and if the user passed `confirmation: 'yes'`. Technically this can be another option in `Install.from_hash` call

---

I think make sense to discuss the more common question, should we use a logging library with the ability to turn on/off logs on demand, something like https://github.com/TwP/logging

@ronaldtse @alexeymorozov how do you think?

**Comment by ronaldtse** [comment]
@CAMOBAP agree, we should have a `--verbose` option and possibly supporting multiple levels of verbosity.

**Comment by CAMOBAP** [comment]
@ronaldtse @alexeymorozov any suggestion about logging library which we can use?

From what I just found:
 - https://github.com/ruby/logger - support levels
 - https://github.com/TwP/logging - support level + allow to turn off specific classes

**Comment by alexeymorozov** [comment]
Currently all logging is done via [`Fontist::Utils::UI`](https://github.com/fontist/fontist/blob/main/lib/fontist/utils/ui.rb)

I see the following options:

1. Implement an option to configure log level, like `Fontist.log_level = :fatal` to turn off all current messages
2. For better consistency with other libraries, replace the logging mechanism with the Logger class, so it can be set like `Fontist.logger.log_level`, and the log calls can be found by the `Fontist.logger.info/error` lines

The first one is fast to implement, the second requires to replace all log calls. In my opinion, both are pretty simple to implement.

Can we keep (incapsulate) the log mechanism in fontist, or we'd prefer to directly work with the logger object in metanorma?

**Comment by alexeymorozov** [comment]
Made a [PR](https://github.com/fontist/fontist/pull/277) with the changes.

After merging, by default it would avoid printing anything to stdout, which can be changed by:

```ruby
Fontist.log_level = :info
```

Also CLI would continue to print its log messages.

@CAMOBAP How do you think? Would it help?

**Comment by CAMOBAP** [comment]
@alexeymorozov looks great! Thanks
