### ISSUE TITLE
SHA256 checksum validation fails for font "Space Mono"

### ISSUE THREAD

**Issue by kickoke** [fontist/fontist#283]
I wanted to build an OGC document using Metanorma. The build worked a month ago. Today, I wanted to build the document again and encountered the following error: 

```
/usr/local/bundle/gems/fontist-1.13.0/lib/fontist/utils/downloader.rb:39:in `raise_if_tampered': 
The downloaded file from https://fonts.google.com/download?family=Space%20Mono doesn't 
match with the expected sha256 checksum (9bc44498e3b559a3a1289ca5baab124e3ef04bd476e2cf53f553a32a60b31bf3)! 
(Fontist::Errors::TamperedFileError)

```

**Comment by alexeymorozov** [comment]
Updated the checksum of Space Mono. Should work now.

There would be no such error in future releases of metanorma since the latest version of fontist has already been changed to emit a warning instead of a failure on a checksum mismatch.

**Comment by kickoke** [comment]
Thank you!
