### ISSUE TITLE
fontist failing in Ruby 3.0

### ISSUE THREAD

**Issue by opoudjis** [fontist/fontist#297]
https://github.com/metanorma/metanorma/runs/7386946312?check_suite_focus=true

**Comment by opoudjis** [comment]
This is still not working

**Comment by ronaldtse** [comment]
@maxirmx could you help check this issue in the seven_zip_ruby gem? It's not been updated since 2020 but somehow it's failing to load 7z.so. Ruby 3.0 is likely not updated as well.

```
An error occurred while loading spec_helper.
Failure/Error: require "fontist"

RuntimeError:
  Failed to find 7z.dll or 7z.so
# ./vendor/bundle/ruby/3.0.0/gems/seven_zip_ruby-1.3.0/lib/seven_zip_ruby.rb:12:in `find_external_lib_dir'
# ./vendor/bundle/ruby/3.0.0/gems/seven_zip_ruby-1.3.0/lib/seven_zip_ruby.rb:17:in `<module:SevenZipRuby>'
# ./vendor/bundle/ruby/3.0.0/gems/seven_zip_ruby-1.3.0/lib/seven_zip_ruby.rb:5:in `<top (required)>'
# ./vendor/bundle/ruby/3.0.0/gems/excavate-0.3.0/lib/excavate/extractors/seven_zip_extractor.rb:1:in `require'
# ./vendor/bundle/ruby/3.0.0/gems/excavate-0.3.0/lib/excavate/extractors/seven_zip_extractor.rb:1:in `<top (required)>'
# ./vendor/bundle/ruby/3.0.0/gems/excavate-0.3.0/lib/excavate/extractors.rb:7:in `require_relative'
# ./vendor/bundle/ruby/3.0.0/gems/excavate-0.3.0/lib/excavate/extractors.rb:7:in `<top (required)>'
# ./vendor/bundle/ruby/3.0.0/gems/excavate-0.3.0/lib/excavate.rb:4:in `require_relative'
# ./vendor/bundle/ruby/3.0.0/gems/excavate-0.3.0/lib/excavate.rb:4:in `<top (required)>'
# ./vendor/bundle/ruby/3.0.0/gems/fontist-1.14.2/lib/fontist/font_installer.rb:2:in `require'
# ./vendor/bundle/ruby/3.0.0/gems/fontist-1.14.2/lib/fontist/font_installer.rb:2:in `<top (required)>'
# ./vendor/bundle/ruby/3.0.0/gems/fontist-1.14.2/lib/fontist/font.rb:1:in `require'
# ./vendor/bundle/ruby/3.0.0/gems/fontist-1.14.2/lib/fontist/font.rb:1:in `<top (required)>'
# ./vendor/bundle/ruby/3.0.0/gems/fontist-1.14.2/lib/fontist.rb:11:in `require'
# ./vendor/bundle/ruby/3.0.0/gems/fontist-1.14.2/lib/fontist.rb:11:in `<top (required)>'
# ./lib/metanorma/compile.rb:5:in `require'
# ./lib/metanorma/compile.rb:5:in `<top (required)>'
# ./lib/metanorma.rb:11:in `require'
# ./lib/metanorma.rb:11:in `<top (required)>'
# ./spec/spec_helper.rb:4:in `require'
# ./spec/spec_helper.rb:4:in `<top (required)>'
No examples found.
No examples found.


Finished in 0.00005 seconds (files took 0.70447 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

I suspect this issue is due to recent changes in Rubygems that changed native library loading. It works on Windows but fails on Ubuntu and macOS.

**Comment by maxirmx** [comment]
As far as I remember ```seven_zip_ruby``` uses its own 'unconventional' method of library loading
I will look at this issue

**Comment by maxirmx** [comment]
Well
It looks like each run differs https://github.com/fontist/fontist/runs/7524211048?check_suite_focus=true
It happens on all platforms sometimes

**Comment by ronaldtse** [comment]
You're right, in fact, it does seem to happen on Ruby 3.0 and 3.1 (occasionally) ubuntu + macOS.

**Comment by maxirmx** [comment]
seven_zip_ruby issue can is fixed by adding  ```spec.add_runtime_dependency "seven_zip_ruby", "~> 1.0"``` to gemspec

**Comment by ronaldtse** [comment]
@maxirmx can we add that gemspec change to the fontist gem instead? Rather not pollute Metanorma. Thanks.

**Comment by maxirmx** [comment]
@ronaldtse 
```seven_zip_ruby``` is used by ```excavate``` which is used by ```fontist``` which is used by ```metanorma```
```excavate``` has a reference to ```seven_zip_ruby``` in  its gemspec

However,  in Ruby 3.0  LOAD_PATH that is acceptable for ```seven_zip_ruby``` is constructed only if ```seven_zip_ruby``` is referenced in the topmost gemspec. I did not look into details but it is looks like bundler fixing gemloader issues
So, when I add that gemspec change to ```fontist``` it helps fontists but not gems that reference ```fontist```

If you do not what to patch metanorma the other solution would be to construct LOAD_PATH for ```seven_zip_ruby``` in ```excavate ``` and then release ```excavate``` and ```fontist```. It can be done of course, but will require to consider and fix other things since both ```excavate``` and ```fontist``` builds are broken

**Comment by ronaldtse** [comment]
> If you do not what to patch metanorma the other solution would be to construct LOAD_PATH for seven_zip_ruby in excavate and then release excavate and fontist. It can be done of course, but will require to consider and fix other things since both excavate and fontist builds are broken.

We do need to fix both gems. It would be great if you can help.

The author for seven_zip_ruby is still active and I can try to contact him. I think the best solution here is to create a PR for seven_zip_ruby that fixes this issue, and potentially also provide fixes for newer Ruby versions via our fork:
https://github.com/fontist/seven_zip_ruby

**Comment by ronaldtse** [comment]
Thank you @maxirmx !
