### ISSUE TITLE
Handle SIGTTOU, SIGTTIN as well as EBADF exception, fail gracefully if detached or lacking terminal

### ISSUE THREAD

**Issue by ronaldtse** [fontist/fontist#305]
As per https://github.com/metanorma/mn-samples-itu/issues/149#issuecomment-1252298808

This is being addressed in #304.

**Comment by maxirmx** [comment]
EBADF is handled by #304
It looks like SIGTTOU, SIGTTIN cannod be processed by Ruby application.  It looks like some Ruby limitation.
