### ISSUE TITLE
Font downloading issues

### ISSUE THREAD

**Issue by abunashir** [fontist/fontist#306]
Hi there, I just saw that in the CI that we are having some issue to download some fonts. I've checked the releases for `noto` fonts and it seems to be there, most likely it's related to GitHub's availability.

<img width="1036" alt="Screenshot 2022-10-11 at 18 46 03" src="https://user-images.githubusercontent.com/1220911/195152000-fb84b120-9890-4782-bc29-2623737c4e04.png">

Should we consider gracefully handling this sorts of issue if the download links aren't available or maybe have some alternative URLs? [Here is the link for the build](https://github.com/metanorma/bipm-si-brochure/actions/runs/3228433127/jobs/5284522051)

//cc: @alexeymorozov, @ronaldtse

**Comment by ronaldtse** [comment]
@maxirmx is this issue still present? Do we need to update Fontist?

**Comment by maxirmx** [comment]
It looks like the same as virtualbox issue we recently fixed but I am not sure.
@abunashir  do you recall how you ran into it ?

**Comment by abunashir** [comment]
I think - I came across that in one of our CI build, not necessarily I had it locally but the CI was failing to download that font.

**Comment by maxirmx** [comment]
@ronaldtse 

- The error log @abunashir  referenced in the original message came from mn2pdf. It is not fontist.
- I believe that handling of negative scenarios there can be improved.  Cases like "could not download file"  or "could not unzip file" etc. I looks like that such error are handled locally in mn2pdf/Util.js  but not propagated updtream.  I guess it requires some kind of design decision. For example, what would we like to do if the file failed to download - "fail globally", "retry", "retry N times",  "ask user"  .... ?

Shall we pass it to @Intelligent2013 ?

**Comment by ronaldtse** [comment]
Yes we should move the task to mn2pdf. I think it possible mn2pdf should not manage fonts itself but rely on Fontist.

**Comment by maxirmx** [comment]
Created [an issue in mn2pdf](https://github.com/metanorma/mn2pdf/issues/200)
