### ISSUE TITLE
Don't ask for --size-limit if resource already in download cache

### ISSUE THREAD

**Issue by CAMOBAP** [fontist/fontist#326]
### Intro

For big formulas' resources fontist request `--size-limit` to download it which is reasonable 

### Problem

if you run `fontist install ...` for the second time and formulas' resource is downloaded already, fontist still require `--size-limit` with error message bellow:

> There are only formulas above the size limit (300 MB). Please specify higher `--size-limit`, or use the `--newest` or `--smallest` options.

### Proposed solution

If resource is downloaded already don't ask user for `--size-limit`

**Comment by ronaldtse** [comment]
Done in #326.
