### ISSUE TITLE
is it possible to change the fonts install path?

### ISSUE THREAD

**Issue by bam80** [fontist/fontist#329]
I need the fonts to be installed in `.local/share/fonts/` so my Flatpacks could find them:
https://github.com/flatpak/flatpak/issues/4097#issuecomment-1262263068

**Comment by ronaldtse** [comment]
Technically it is already possible to change the font install path:
* https://github.com/fontist/fontist#configuration

> By default Fontist uses the `~/.fontist` directory to store fonts and its files. It could be changed with the `FONTIST_PATH` environment variable.

```
FONTIST_PATH=~/.fontist_new fontist {command}
```

Are you thinking of a persistent path setting like:

```
fontist set-install-path {my-fontist-path}
```
?

**Comment by ronaldtse** [comment]
@alexeymorozov can I have your thoughts here? Thanks.

**Comment by alexeymorozov** [comment]
I think, `fontist` could have such a config option so it would be easier to use it from CLI. I'll implement it.

**Comment by alexeymorozov** [comment]
The feature is implemented now. So, instead of a symlink, the following command can be used:

```
fontist config set fonts_path {my-fonts-path}
```

For example:

```
fontist config set fonts_path .local/share/fonts/flatpak-workaround
```
