### ISSUE TITLE
Default macOS font `NISC18030` (GB18030) raising errors

### ISSUE THREAD

**Issue by ronaldtse** [fontist/fontist#344]
The default macOS font `NISC18030.ttf` (I'm on Sonoma 14.0) raises errors as follows:

```
WARNING: error in the font '~/.metanorma/fonts/NISC18030.ttf' registering.
...
```

This error occurs here:
* https://github.com/metanorma/metanorma-ogc/issues/600

This is a stock font to macOS:
* https://support.apple.com/en-us/HT201344

It looks like this error is inherent to this particular macOS font, e.g.:
* https://github.com/matplotlib/matplotlib/issues/7305/

Apparently this is the "GB18030 Bitmap (NISC18030)" font, which is a Simplified Chinese font.

This font is broken by default that is not TrueType compliant:
* https://lists.gnu.org/archive/html/cjk-list/2013-07/msg00024.html

> Apple indeed ships a broken font since it doesn't conform to Apple's
> own TrueType standard
> (https://developer.apple.com/fonts/TTRefMan/RM06/Chap6head.html): The
> `magic number' in the `bhed' table should be 0x5F0F3CF5, however, in
> this font it is 0x000000FF.

Some software like XQuartz (which is from Apple) just specifically ignore it:
* https://github.com/XQuartz/XQuartz/issues/304
    * https://github.com/XQuartz/XQuartz/commit/bdfd1120f7d3aa4ef966084cc4209f0ca63e8fd2
* https://github.com/XQuartz/XQuartz/issues/216#issuecomment-1406051957

I wonder what our solution should be.

There are two questions:
1. When/why do we need this font? Ping @intelligent2013
2. Should we parse this font in Fontist, or ignore it like XQuartz does?

**Comment by Intelligent2013** [comment]
> 1. When/why do we need this font? Ping @Intelligent2013

We don't need this font. Looks like this font was installed together with another fonts (in one package/.zip) once and `mn2pdf` tries to register all fonts which present in the folder `~/.metanorma/fonts/...`. I'll modify `mn2pdf` to register the fonts only that really is using in fontist manifest.

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !

**Comment by Intelligent2013** [comment]
Investigation from https://github.com/metanorma/mn2pdf/issues/226#issuecomment-1794564783:

> Very interestingly, `mn2pdf` already registers the fonts which are using in the fontist manifest, not all fonts. `mn2pdf` uses the path `~/.fontist/fonts`, but not `~/.metanorma/fonts`. The message
> 
> ```
> WARNING: error in the font '/.metanorma/fonts/NISC18030.ttf' registering.
> ```
> 
> means that the font `NISC18030.ttf` presents in the passed fontist manifest `--font-manifest "/var/folders/2t/xmdrn2sd2lv2w49dv0zw9_q00000gp/T/fontist_locations20231101-43877-pzirxr.yml"`. But how did it get there...
> 
> The `https://github.com/metanorma/metanorma-ogc/blob/main/lib/metanorma/ogc/processor.rb` doesn't contains NISC18030 (or GB18030) font:
> 
> ```ruby
>       def fonts_manifest
>         {
>           "Lato" => nil,
>           "Lato Light" => nil,
>           "Arial" => nil,
>           "STIX Two Math" => nil,
>           "Source Han Sans" => nil,
>           "Source Han Sans Normal" => nil,
>           "Fira Code" => nil,
>           "Courier New" => nil,
>           "Times New Roman" => nil,
>           "Overpass" => nil,
>           "Space Mono" => nil,
>         }
>       end
> ```

**Comment by ronaldtse** [comment]
GB18030 is only used for Simplified Chinese. So when different Metanorma flavors use different languages, we will need different fonts as well.

In this case, I believe OGC doesn't need the Simplified Chinese font right now.

**Comment by alexeymorozov** [comment]
I can make Fontist avoid using "NISC18030.ttf" by checking its magic number, since:
1. we don't need this font right now
2. Java could not work with it anyway
3. and even some software (XQuartz) already ignores it

To investigate further, obtaining an original `adoc` file would help a lot, so it can be reproduced locally to find out where the font appears for the first time: in a requested manifest, in a response manifest, or in mn2pdf.

**Comment by ronaldtse** [comment]
@alexeymorozov in this case let's create a "font skip list" that we skip this particular font.

We also need to document a list of "known problematic fonts" on our website.

**Comment by ronaldtse** [comment]
Closing since PRs are merged.
