### ISSUE TITLE
Create a setup-fontist GitHub Action

### ISSUE THREAD

**Issue by jcbhmr** [fontist/fontist#350]
Hello! 👋

While searching for tools to install fonts on GitHub Actions runners to answer https://github.com/typst-community/setup-typst/issues/14 I came across fontist as a way to easily add more fonts from Google Fonts.

```sh
fontist install "Fira Code"
typst fonts --font-path ~/.fontist/fonts # reports that Fira Code is available!
```

However... In order to recommend this to users, I'd very much like a one-liner `- uses: fontist/setup-fontist@v1` or similar GitHub Actiton so that I can say something like:

> Need additional fonts for your Typst paper? You can use [Fontist](#) to install them! Here's an example:
>
> ```yml
> - uses: typst-community/setup-typst@v3
> - uses: fontist/setup-fontist@v1
> - run: fontist install "Fira Code"
> - run: typst compile paper.typ --font-path ~/.fontist/fonts
> ```
>
> 📚 Read more about [fontist/setup-fontist]()
> 📚 Read more about [Fontist]()

or something. Right now you need to manually install Ruby using https://github.com/ruby/setup-ruby and then `gem install fontist`. That's like 4-5 lines with configuration decisions that you need to make when it should be a oneliner lol

Here's my attempt at a basic setup-fontist action. https://github.com/jcbhmr/setup-fontist
see https://github.com/github/setup-licensed for a better example of a Ruby gem github action

<sup> ❤️ id be very willing to Transfer the repo to the @fontist org</sup>

**Comment by ronaldtse** [comment]
@jcbhmr thank you for the contribution and the offer to transfer!!

Indeed, a one-liner is what we should do. We would definitely love to advertise this action to our users. We would be more than willing to maintain and enhance the action moving forward in order to support the Typst community.

Thank you once again for this awesome work 👍

**Comment by jcbhmr** [comment]
Awesome! ❤️ 👍  I requested to transfer https://github.com/jcbhmr/setup-fontist to @ronaldtse . (I can't directly Transfer it to @fontist since I don't repo-create perms -- i.e. im not a member -- so I transfered it to you and you can Transfer it to @fontist or whatever else you want to do with it.)

The https://github.com/jcbhmr/setup-fontist repository is published to GitHub Actions Marketplace as "Setup Fontist" https://github.com/marketplace/actions/setup-fontist

**Comment by ronaldtse** [comment]
The action is now at https://github.com/fontist/setup/ . Thank you @jcbhmr for the fantastic contribution!!
