### ISSUE TITLE
libsmpack failing to install in Windows GHA

### ISSUE THREAD

**Issue by opoudjis** [fontist/fontist#361]
https://github.com/metanorma/metanorma-ieee/actions/runs/7870385649/job/21471466801?pr=343

Fontist has recently added the libsmpack gem. This gem is failing to install in Github Actions for Windows environments: the gem is failing to compile to a native executable.

**Comment by CAMOBAP** [comment]
Should be fixed after https://github.com/fontist/excavate/pull/26 release

Let me doublecheck

**Comment by CAMOBAP** [comment]
[According to logs](https://github.com/metanorma/metanorma-ieee/actions/runs/7870385649/job/21471466801?pr=343#step:4:1495) it install `ffi-compiler2 2.0.1` but for some reason still do use `ffi-compiler2 2.2.1` during native extenstion compilation

Probably cache need to be dropped, looking for a way to do it locally

**Comment by CAMOBAP** [comment]
Cache dropped re-run in progress https://github.com/metanorma/metanorma-ieee/actions/runs/7870385649

**Comment by opoudjis** [comment]
Thank you @CAMOBAP !
