### ISSUE TITLE
(URGENT) Crashes in Fontist on GHA

### ISSUE THREAD

**Issue by ronaldtse** [fontist/fontist#367]
From @ghobona at https://github.com/metanorma/metanorma-ogc/issues/651

Error 1:
```
/usr/local/bundle/gems/fontist-1.20.0/lib/fontist/font.rb:220:in `request_formula_installation': undefined method `each' for nil:NilClass (NoMethodError)

      paths.each do |path|
           ^^^^^
	from /usr/local/bundle/gems/fontist-1.20.0/lib/fontist/font.rb:207:in `block in download_font'
	from /usr/local/bundle/gems/fontist-1.20.0/lib/fontist/font.rb:206:in `each'
```

Error 2:
```
/usr/local/bundle/gems/fontist-1.20.0/lib/fontist/indexes/base_index.rb:9:in `from_yaml': Please fetch formulas with `fontist update`. (Fontist::Errors::MainRepoNotFoundError)
	from /usr/local/bundle/gems/fontist-1.20.0/lib/fontist/formula.rb:82:in `find_by_font_file'
	from /usr/local/bundle/gems/fontist-1.20.0/lib/fontist/system_index.rb:217:in `override_font_props'
	from /usr/local/bundle/gems/fontist-1.20.0/lib/fontist/system_index.rb:213:in `parse_font'
```

**Comment by ronaldtse** [comment]
@alexeymorozov can you please help with this? Thanks.

**Comment by alexeymorozov** [comment]
Temporarily as a hotfix and a test case I've replaced the current formula with 4 others for each style with urls which the site uses. I've tried and it works in [my fork](https://github.com/alexeymorozov/ogcna-auto-review/actions/runs/8545679553/job/23414478914). The fix is already in the formulas repo so the opengeospatial's repo should work too now.

But we need a proper fix because, as far as I see, all google formulas stopped working. The current archive URL returns javascript which calls API and gets urls for each font style, then downloads them and archives in a zip file after.

API with urls for styles: https://fonts.google.com/download/list?family=Space+Mono

More information on the Google's change: https://github.com/google/fonts/issues/7481

How people are dealing with the change: https://github.com/squidfunk/mkdocs-material/issues/6983

**Comment by ronaldtse** [comment]
@alexeymorozov I think we have two problems to deal with:
1. Fetching and indexing Google Fonts into Formulas
2. Allowing Fontist users to directly download fonts from Google Fonts in a non-interactive way

For 1, the best choice has to be directly parsing the [google/fonts](https://github.com/google/fonts) GitHub repository. Changes there may be more frequent than their new Developer API, but also means we can respond to them faster. It would mean we need to parse font metadata ourselves, but that's also reasonable because we need that functionality for fonts sourced outside of Google Fonts.

For 2, users have two needs with Google Fonts:
* Downloading the font file locally. We can link people to the Google Fonts GitHub.
* Providing an HTTP link for web rendering. This we don't serve yet, and we will need to have the WOFF-type link to make this happen. The WOFF file and link are not provided in the GitHub repository, so we will need to use the Developer API.

Conclusion: 
1. For most of Formula information, we can populate from their GitHub repository, including for local font download.
2. For public usage of the font we will need to use the API for every font to obtain the public-facing font file links and WOFF links.

Regarding 1:

Interestingly, their metadata file (`METADATA.pb` in text protobuf) looks eerily similar to our Formula file:
* https://github.com/google/fonts/blob/main/ofl/abhayalibre/METADATA.pb

Except that they have:
* per font `weight`
* `designer`
* `category`: `SERIF`, `SANS_SERIF`, `DISPLAY`, `MONOSPACE`, ...
* `primary_script`
* `subsets`
* optional `classifications`
* optional `stroke`
* optional `source`: lists where the repository/commit the font file and/or archive is from. If there is `source` they have an `upstream.yaml` file that lists out:
  * for repository: which branch, location of the license file, location of the TTF file inside that source repository.
  * for archive: URL and location of the license and TTF files
  * NOTE: They have a [PR](https://github.com/google/fonts/pull/7517) that merges upstream.yaml into METADATA.pb

They also have `DESCRIPTION.{lang}.html` that provides a description of the font, in HTML. Perhaps we should also supply this on the Formulas site.

Maybe having this information would also be a good choice for Fontist...

**Comment by ronaldtse** [comment]
This is done.
