### ISSUE TITLE
Update the Google Fonts indexing mechanism

### ISSUE THREAD

**Issue by ronaldtse** [fontist/fontist#370]
I think we have two problems to deal with:
1. Fetching and indexing Google Fonts into Formulas
2. Allowing Fontist users to directly download fonts from Google Fonts in a non-interactive way

For 1, the best choice has to be directly parsing the [google/fonts](https://github.com/google/fonts) GitHub repository. Changes there may be more frequent than their new Developer API, but also means we can respond to them faster. It would mean we need to parse font metadata ourselves, but that's also reasonable because we need that functionality for fonts sourced outside of Google Fonts.

For 2, users have two needs with Google Fonts:
* Downloading the font file locally. We can link people to the Google Fonts GitHub.
* Providing an HTTP link for web rendering. This we don't serve yet, and we will need to have the WOFF-type link to make this happen. The WOFF file and link are not provided in the GitHub repository, so we will need to use the Developer API.

Conclusion: 
1. For most of Formula information, we can populate from their GitHub repository, including for local font download.
2. For public usage of the font we will need to use the API for every font to obtain the public-facing font file links and WOFF links.

Regarding 1:

Interestingly, their metadata file (`METADATA.pb` in text protobuf) looks eerily similar to our Formula file:
* https://github.com/google/fonts/blob/main/ofl/abhayalibre/METADATA.pb

Except that they have:
* per font `weight`
* `designer`
* `category`: `SERIF`, `SANS_SERIF`, `DISPLAY`, `MONOSPACE`, ...
* `primary_script`
* `subsets`
* optional `classifications`
* optional `stroke`
* optional `source`: lists where the repository/commit the font file and/or archive is from. If there is `source` they have an `upstream.yaml` file that lists out:
  * for repository: which branch, location of the license file, location of the TTF file inside that source repository.
  * for archive: URL and location of the license and TTF files
  * NOTE: They have a [PR](https://github.com/google/fonts/pull/7517) that merges upstream.yaml into METADATA.pb

They also have `DESCRIPTION.{lang}.html` that provides a description of the font, in HTML. Perhaps we should also supply this on the Formulas site.

Maybe having this information would also be a good choice for Fontist...

_Originally posted by @ronaldtse in https://github.com/fontist/fontist/issues/367#issuecomment-2035897013_

**Comment by ronaldtse** [comment]
@alexeymorozov I have added the secret `FONTIST_CI_GOOGLE_FONTS_API_KEY` in the Fontist GitHub organization to allow for using the Google Fonts API.

**Comment by opoudjis** [comment]
This is now holding up release, so it is urgent.

**Comment by ronaldtse** [comment]
Thank you @alexeymorozov . It looks like the "Trispace" font has 5 variants in the archive/our formula:
* "Trispace": Regular / Bold / Italics / Light / Thin / ExtraBold / ExtraLight / Medium / SemiBold
* "TrispaceCondensed"
* "TrispaceSemiCondensed"
* "TrispaceExpanded"
* "TrispaceSemiExpanded"

I wonder if Google Fonts simply split it into 5 fonts?

**Comment by ronaldtse** [comment]
@alexeymorozov regarding Trispace: all of the TTF files exist in the source repo:
https://github.com/Etcetera-Type-Co/Trispace/tree/master/fonts/static/ttf

<img width="988" alt="Screenshot 2024-04-20 at 15 00 54" src="https://github.com/fontist/fontist/assets/11865/0ed8e0e6-fe0e-4396-afda-6ee3bd590d94">

In the Google Fonts repo, it seems that they have some issue with data accuracy:
* https://github.com/google/fonts/blob/8c9a9848eaf9e3f7ccc7502fef84936ec1ca5650/ofl/trispace/METADATA.pb#L11

On this line it says the `post_script_name: Trispace-Thin`, which is clearly untrue.

However, I downloaded Google Font's Trispace font:
https://github.com/google/fonts/blob/main/ofl/trispace/Trispace%5Bwdth%2Cwght%5D.ttf

It does contain all the weights for the "regular" font, but it does not contain the Condensed/SemiCondensed/Expanded/SemiExpanded fonts:
<img width="500" alt="Screenshot 2024-04-20 at 15 04 09" src="https://github.com/fontist/fontist/assets/11865/0fa97dc5-b806-4ad5-9603-175be68702b4">

I think either we create a PR to Google Fonts that adds these 4 fonts, or just ignore this problem for now.

**Comment by ronaldtse** [comment]
I've reported this problem here:
* https://github.com/google/fonts/issues/7585

**Comment by alexeymorozov** [comment]
While I'm finishing with the import from the google/fonts repo, I propose we also do the import from the API.

API contains 6129 font files, at least 2945 of them are additional to the repo. In the repo there are 3377 font files.

Another thing - for purposes of downloading from API, checking the font files in the API may provide additional accuracy, because files in the repo and in the API may be different even when have the same style/weight. E.g. in the repo a file may be a variable one but in the API it is a regular one.

API data: https://www.googleapis.com/webfonts/v1/webfonts?key=API_KEY

I'm attaching files containing lists of fonts in the repo and the API:
[repofonts.json](https://github.com/fontist/fontist/files/15276242/repofonts.json)
[apifonts.json](https://github.com/fontist/fontist/files/15276241/apifonts.json)

**Comment by alexeymorozov** [comment]
Released v1.21.1 with the feature. New formulas are on the `v4` branch so I propose we make it the default one.

After users update to the new fontist, in order for the feature to work it's needed to run `fontist update`.

**Comment by ronaldtse** [comment]
@alexeymorozov please feel free to close this issue when complete, thanks!
