### ISSUE TITLE
Unable to download font from GitHub releases due to SSL error

### ISSUE THREAD

**Issue by ronaldtse** [fontist/fontist#373]
https://github.com/metanorma/mn-samples-iso/actions/runs/8828785719/job/24238434563

```
/__tebako_memfs__/lib/ruby/gems/3.1.0/gems/fontist-1.20.0/lib/fontist/font_installer.rb:95:in `download_file': Invalid URL: https://github.com/fontist/source-fonts/releases/download/v1.0/source-fonts-1.0.zip. Error: #<Down::SSLError: SSL_connect SYSCALL returned=5 errno=0 peeraddr=140.82.116.4:443 state=error: certificate verify failed>. (Fontist::Errors::InvalidResourceError)
```

The link is:
* https://github.com/fontist/source-fonts/releases/download/v1.0/source-fonts-1.0.zip

Also described here (not sure if it's an issue there or there):
* https://github.com/tamatebako/tebako/issues/146

**Comment by alexeymorozov** [comment]
Investigated a little but with no significant progress:

1. Fontist successfully installs the font locally
2. At GHA Fontist's specs with this font also works
3. Locally metanorma successfully uses fontist to install the font

I'll try to run metanorma with and without tebako at GHA and then search for possible solutions.

Other findings: I found out and remembered that `packed-mn` has an SSL fix for Windows. Though it should not affect macOS builds, it could be a starting point for debugging and fixing:

https://github.com/metanorma/packed-mn/blob/main/bin/metanorma#L56
```ruby
    def use_ssl= boolean
      self.ca_file = "#{File.expand_path(File.dirname(__FILE__))}/cacert.pem.mozilla"
      self.verify_mode = OpenSSL::SSL::VERIFY_PEER
      self._use_ssl = boolean
    end
```

**Comment by ronaldtse** [comment]
This is fixed in https://github.com/tamatebako/tebako/issues/146 . Thanks.
