### ISSUE TITLE
(URGENT) Fontist failing to install `noto_sans_jp` and `noto_sans`?

### ISSUE THREAD

**Issue by ronaldtse** [fontist/fontist#377]
From:
* https://github.com/metanorma/mn-samples-plateau/issues/16
* https://github.com/metanorma/metanorma-plateau/issues/2#issuecomment-2127969463

```
Downloading font "google/noto_sans_jp" from https://fonts.google.com/download?family=Noto%20Sans%20JP
Downloading:   0% (0/33 MiB), 0.05 MiB/s, done.
Installing font "google/noto_sans_jp".
Fonts installed at:
bundler: failed to load command: metanorma (~/.asdf/installs/ruby/3.2.2/bin/metanorma)
~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fontist-1.20.0/lib/fontist/font.rb:220:in `request_formula_installation': undefined method `each' for nil:NilClass (NoMethodError)

      paths.each do |path|
           ^^^^^
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fontist-1.20.0/lib/fontist/font.rb:207:in `block in download_font'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fontist-1.20.0/lib/fontist/font.rb:206:in `each'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fontist-1.20.0/lib/fontist/font.rb:206:in `flat_map'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fontist-1.20.0/lib/fontist/font.rb:206:in `download_font'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fontist-1.20.0/lib/fontist/font.rb:57:in `install'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fontist-1.20.0/lib/fontist/font.rb:34:in `install'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fontist-1.20.0/lib/fontist/manifest/install.rb:25:in `install_font'
```

**Comment by alexeymorozov** [comment]
Replaced the following fonts from the google formulas:

- Noto Sans JP (Regular, Bold)
- Noto Sans (Regular, Italic, Bold, Bold Italic)
- Noto Sans Condensed (Regular, Italic, Bold, Bold Italic)
- other Noto Sans variations

Since Noto Sans Condensed could not be found at Google Fonts (neither website, nor API), I've used the following package:
https://github.com/notofonts/latin-greek-cyrillic/releases/tag/NotoSans-v2.013

`fontist update` is required before the first usage. It should work now.

**Comment by ronaldtse** [comment]
> Since Noto Sans Condensed could not be found at Google Fonts (neither website, nor API), I've used the following package:

Wow that's crazy. The new Google Fonts API is losing plenty of data... Not a problem we have resources to solve though...

**Comment by ronaldtse** [comment]
Closing. Thank you @alexeymorozov !
