### ISSUE TITLE
URGENT: Font required for metanorma-bipm is invalid

### ISSUE THREAD

**Issue by opoudjis** [fontist/fontist#382]
https://github.com/metanorma/metanorma-cli/actions/runs/10244795419/job/28340978101

Attempting to compile the files in mn-samples-bipm is triggering the following error:

````
/Users/runner/work/metanorma-cli/metanorma-cli/samples/vendor/bundle/ruby/3.1.0/gems/fontist-1.21.1/lib/fontist/resources/archive_resource.rb:32:in `download_file': 
Invalid URL: https://www.gust.org.pl/projects/e-foundry/tex-gyre/whole/tg2_501otf.zip. Error: #<Down::ServerError: 502 Bad Gateway>. (Fontist::Errors::InvalidResourceError)
````

The fonts BIPM accesses are:

          "Arial" => nil,
          "Times New Roman" => nil,
          "Work Sans" => nil,
          "Work Sans Black" => nil,
          "Work Sans ExtraBold" => nil,
          "Work Sans ExtraLight" => nil,
          "Work Sans Light" => nil,
          "Work Sans Medium" => nil,
          "Work Sans SemiBold" => nil,
          "Work Sans Thin" => nil,
          "STIX Two Math" => nil,
          "Source Han Sans" => nil,
          "Source Han Sans Normal" => nil,
          "TeXGyreChorus" => nil,

Presumably this is TeXGyreChorus. https://www.gust.org.pl/projects/e-foundry/tex-gyre/whole/tg2_501otf.zip is indeed inaccessible.

**Comment by opoudjis** [comment]
This is blocking Metanorma release, and must be resolved as a matter of urgency.

**Comment by opoudjis** [comment]
To prevent recurrence of this on test day: @CAMOBAP would it be possible to set up a cron job that checks all the URLs Metanorma invokes in Fontist daily? The fonts are listed in https://github.com/fontist/fontist/wiki/Font-usage-in-Metanorma

**Comment by CAMOBAP** [comment]
@opoudjis what is your vision about the implementation of this check? Should it be done in a single place, or can be 'distributed' across `metanorma-*` maybe as an unit test?

@alexeymorozov AFAIR some metanorma testing was don't on `fontist` side maybe you have also some vision/suggestions where/how implement testing of release-critical font formulas?

**Comment by opoudjis** [comment]
I think it's a weekly check, in one place, of just the fonts that Metanorma accesses, to ensure that if any of those fonts have become unavailable, @alexeymorozov is notified. Of course, Alexei can say what works best for him, but now that more repos are must-pass for Metanorma, this is going to become more of an issue.

**Comment by CAMOBAP** [comment]
> It can just be a ping of the URLs involved

to ping them we will have to maintain a list of those URLs, they are already presented in the formulas, so it is better test the formulas installation itself because there is possible not only 404 but corrupted files too.

On the other side list of fonts used by metanorma-* are in `Metanorma::*::Processor.fonts_manifest` methods. So we can write a simple tool that `require metanorma/*/processor` and feed `Fontist::CLI` with `fonts_manifest` map

If put it on `metanorma`org's side, I think better place is `metanorma-cli` otherwise `fontist` repo

@alexeymorozov any feedback from your side is appreciated

**Comment by andrew2net** [comment]
Relaton also has the error here https://github.com/relaton/relaton-data-bipm/actions/runs/10250502470/job/28356370174#step:7:575

**Comment by ronaldtse** [comment]
It should be done on the Metanorma side indeed. 

@andrew2net but Relaton does not depend on Fontist at all, maybe find out why and remove that dependency?

**Comment by CAMOBAP** [comment]
> It should be done on the Metanorma side indeed.
> 
> @andrew2net but Relaton does not depend on Fontist at all, maybe find out why and remove that dependency?

Ok, I will implement dediсated workflow on metanorma-сli repo https://github.com/metanorma/metanorma-cli/issues/336

**Comment by andrew2net** [comment]
> @andrew2net but Relaton does not depend on Fontist at all, maybe find out why and remove that dependency?

@ronaldtse yes, it doesn't, but matanorma is used in the relation-data-bimp GHA

**Comment by opoudjis** [comment]
If BIPM is the only flavour that fails release now, because of this, I will force release...

**Comment by opoudjis** [comment]
This issue is now also blocking mn-samples-jcgm, now that its plurimath bug has been resolved:

> D:/a/metanorma-cli/metanorma-cli/samples/vendor/bundle/ruby/3.1.0/gems/fontist-1.21.1/lib/fontist/resources/archive_resource.rb:32:in `download_file': Invalid URL: https://www.gust.org.pl/projects/e-foundry/tex-gyre/whole/tg2_501otf.zip. Error: #<Down::ServerError: 502 Bad Gateway>. (Fontist::Errors::InvalidResourceError)

Which is to be expected, JCGM uses the same BIPM gem.

I am going to force release, but this continues to need to be addressed.

**Comment by CAMOBAP** [comment]
https://web.archive.org/web/20210213120450/https://www.gust.org.pl/projects/e-foundry/tex-gyre/whole/tg2_501otf.zip - looks working I will try to update formula ASAP

**Comment by CAMOBAP** [comment]
Formula fixed, retrying failed jobs

**Comment by CAMOBAP** [comment]
https://github.com/metanorma/metanorma-cli/pull/337 - ready for review
