### ISSUE TITLE
Mirrors for Cleartype fonts

### ISSUE THREAD

**Issue by ronaldtse** [fontist/fontist#64]
From @abunashir 
> Seems like the dropbox link and some other files url are missing/has different sha for cleartype_fonts.rb

Maybe these?

* https://nchc.dl.sourceforge.net/project/mscorefonts2/cabs/PowerPointViewer.exe
* https://sourceforge.net/projects/mscorefonts2/files/cabs/PowerPointViewer.exe/download
* https://web.archive.org/web/*/https://download.microsoft.com/download/E/6/7/E675FFFC-2A6D-4AB0-B3EB-27C9F8C8F696/PowerPointViewer.exe

**Comment by abunashir** [comment]
@ronaldtse: I've created a new PR with these changes,
