### ISSUE TITLE
In CLI, prompt user to agree with font licenses when installing fonts

### ISSUE THREAD

**Issue by ronaldtse** [fontist/fontist#68]
The current message doesn't clearly show which font requires the license. The font name "Overpass" is placed at the very end which is confusing.

e.g.
```
Metanorma has detected that you do not have the necessary fonts installed
for PDF generation. The generated PDF will use generic fonts that may not
resemble the desired styling. Metanorma can download these files for you
if you accept the font licensing conditions for the font Overpass.

----------
Copyright 2016 Red Hat, Inc.,

This Font Software is dual licensed under the SIL Open Font License...
----------
If you want Metanorma to download these fonts for you and indicate your
acceptance of the font licenses, type "Yes" / "No": Yes
```

How about we do this?

```
[metanorma/font] detected font "Overpass" missing.
[metanorma/font] detected font "..." missing.
[metanorma/font] detected font "..." missing.

Metanorma has detected that you do not have the necessary fonts installed
for PDF generation. The generated PDF will use generic fonts that may not
resemble the desired styling. Metanorma can download these files for you
if you accept the font licensing conditions.

"Overpass" font license:
----------
Copyright 2016 Red Hat, Inc.,

This Font Software is dual licensed under the SIL Open Font License...
...
----------

"FOO" font license:
----------
Copyright 2016 Red Hat, Inc.,

This Font Software is dual licensed under the SIL Open Font License...
...
----------
...

If you want Metanorma to download these fonts for you and indicate your
acceptance of the font licenses, type "Yes" / "No": Yes
```

**Comment by abunashir** [comment]
@ronaldtse: The displaying part of the license is being handled by [metanorma-cli](https://github.com/metanorma/metanorma-cli/blob/master/lib/metanorma/cli/setup.rb#L70), so should we fix that issue there?

**Comment by abunashir** [comment]
@ronaldtse: The first part is here: https://github.com/metanorma/metanorma-cli/pull/161, Do we also want to group licenses for all fonts in one message? My concern here would be that the combined messages gonna be huge, so rarely that might serve the purpose of showing licenses, Any thoughts?

**Comment by ronaldtse** [comment]
@abunashir do you think it is useful to show the licenses via fontist instead of metanorma? This technically relates to fontist more. And perhaps it would be useful to have a fontist CLI.

**Comment by abunashir** [comment]
I have a mixed feeling about this. Since the current version of the fontist is only a library, can be used by any other tool, so ideally I would recommend not to print out something from it. This way, fontist does require confirmation but gives the user full control of how they want to display the license to its actual user.

I think it might be a good idea to have a CLI at some point, but then again most of our current use cases are through metanorma CLI, and it's easier to deal with a library than a CLI from a CLI. So, Considering these factor I'm not super convinced. What are your thoughts?

**Comment by ronaldtse** [comment]
> I think it might be a good idea to have a CLI at some point, but then again most of our current use cases are through metanorma CLI, and it's easier to deal with a library than a CLI from a CLI. So, Considering these factor I'm not super convinced. What are your thoughts?

I think a CLI is an easy way of using the gem and is very useful especially in testing. For example, the AsciiMath gem has an executable that is only 20 lines long:

https://github.com/asciidoctor/asciimath/blob/949209d2778b2ff57b746386949c69a3e34c9e79/lib/asciimath/cli.rb#L7

With your experience adding a Thor CLI should be rather simple? :wink:

**Comment by ronaldtse** [comment]
Related to #98

**Comment by ronaldtse** [comment]
@alexeymorozov now that we have the CLI, it would be to prompt the user for individual licenses if user didn't provide `accept all licenses` option.

**Comment by alexeymorozov** [comment]
Current behaviour is to prompt to agree for each font. We'd like to ask for confirmation only once?

```
$ cat license.install.yml
Andale Mono:
Arial Black:

$ fontist manifest-install license.install.yml
FONT LICENSE ACCEPTANCE REQUIRED FOR "Andale Mono":

Fontist can install this font if you accept its licensing conditions.

FONT LICENSE BEGIN ("Andale Mono")
-----------------------------------------------------------------------
(from http://web.archive.org/web/20011222020409/http://www.microsoft.com/typography/fontpack/eula.htm)
TrueType core fonts for the Web EULA
END-USER LICENSE AGREEMENT FOR
MICROSOFT SOFTWARE
...
-----------------------------------------------------------------------
FONT LICENSE END ("Andale Mono")

Do you accept all presented font licenses, and want Fontist to download these fonts for you? => TYPE 'Yes' or 'No': yes
Downloading font "andale" from https://gitlab.com/fontmirror/archive/-/raw/master/andale32.exe
Downloads: 0MB/0MB (100.00%) (cache)
Installing font "andale".
Fonts installed at:
- /Users/u/.fontist/fonts/AndaleMo.TTF
FONT LICENSE ACCEPTANCE REQUIRED FOR "Arial Black":

Fontist can install this font if you accept its licensing conditions.

FONT LICENSE BEGIN ("Arial Black")
-----------------------------------------------------------------------
(from http://web.archive.org/web/20011222020409/http://www.microsoft.com/typography/fontpack/eula.htm)
TrueType core fonts for the Web EULA
END-USER LICENSE AGREEMENT FOR
MICROSOFT SOFTWARE
...
-----------------------------------------------------------------------
FONT LICENSE END ("Arial Black")

Do you accept all presented font licenses, and want Fontist to download these fonts for you? => TYPE 'Yes' or 'No': yes
Downloading font "arial_black" from https://gitlab.com/fontmirror/archive/-/raw/master/arialb32.exe
Downloads: 0MB/0MB (100.00%) (cache)
Installing font "arial_black".
Fonts installed at:
- /Users/u/.fontist/fonts/AriBlk.TTF
```

**Comment by alexeymorozov** [comment]
@ronaldtse Please correct me if I'm wrong: the work to done is to add the `--accept-all-licenses` option? Since currently each font is accepted separately, one by one.

**Comment by ronaldtse** [comment]
@alexeymorozov I think there are 2 considerations:
- `--accept-all-licenses` means answering "yes"
- but to "hide" the display of licenses probably we want to have a separate option, such as `--hide-licenses` or global `--quiet`.

Thoughts?

**Comment by alexeymorozov** [comment]
Sounds as a good idea to me. So we get:

1. `--accept-all-licenses` skips prompts but still shows the licenses
2. `--hide-licenses` hides licenses texts

**Comment by ronaldtse** [comment]
Right, so the user needs to supply both options if they want to accept all licenses but also hide them. Thanks!

**Comment by ronaldtse** [comment]
While you’re at it, also:
- ‘--hide-licenses’ when given will hide licenses, but will still prompt for Y/N if it’s the only option

**Comment by alexeymorozov** [comment]
Yeap, implemented exactly this way :)
